import frodoAvatarImg from '../assets/images/character_frodo.jpg';

import enemySpiderAvatar from '../assets/images/enemy_spider.jpg';
import enemyTrollAvatar from '../assets/images/enemy_troll.jpg';
import enemyKnightAvatar from '../assets/images/enemy_knight.jpg';
import enemySauronAvatar from '../assets/images/enemy_sauron.jpg';

export const gameState = {
  player: {
    name: '',
    avatar: '',
    wins: 0,
    loses: 0,
    health: 100,
    maxHealth: 100,
    attack: 10,
    attackZones: 1,
    defendZones: 2,
    critChance: 0.2,
    critMultiplier: 1.5,
  },
  avatars: [
    {
      avatarName: 'frodo',
      health: 100,
      maxHealth: 100,
      attack: 10,
      attackZones: 1,
      defendZones: 2,
      critChance: 0.2,
      critMultiplier: 1.5,
    },
    {
      avatarName: 'aragorn',
      health: 100,
      maxHealth: 100,
      attack: 12,
      critChance: 0.15,
      critMultiplier: 1.25,
      attackZones: 2,
      defendZones: 2,
    },
    {
      avatarName: 'legolas',
      health: 80,
      maxHealth: 80,
      attack: 18,
      critChance: 0.25,
      critMultiplier: 1.35,
      attackZones: 2,
      defendZones: 1,
    },
    {
      avatarName: 'gandalf',
      health: 150,
      maxHealth: 150,
      attack: 15,
      critChance: 0.1,
      critMultiplier: 1.15,
      attackZones: 2,
      defendZones: 2,
    },
  ],
  battle: {
    playerAttack: [],
    playerDefend: [],
    enemyAttack: [],
    enemyDefend: [],
    log: [],
  },
  enemy: {},
  enemies: [
    {
      name: 'Spider',
      avatar: enemySpiderAvatar,
      health: 80,
      maxHealth: 80,
      attack: 12,
      critChance: 0.25,
      critMultiplier: 1.5,
      attackZones: 2,
      defendZones: 1,
    },
    {
      name: 'Troll',
      avatar: enemyTrollAvatar,
      health: 120,
      maxHealth: 120,
      attack: 8,
      critChance: 0.1,
      critMultiplier: 2,
      attackZones: 1,
      defendZones: 3,
    },
    {
      name: 'Knight',
      avatar: enemyKnightAvatar,
      health: 100,
      maxHealth: 100,
      attack: 10,
      critChance: 0.15,
      critMultiplier: 1.5,
      attackZones: 1,
      defendZones: 2,
    },
    {
      name: 'Sauron',
      avatar: enemySauronAvatar,
      health: 150,
      maxHealth: 150,
      attack: 15,
      critChance: 0.15,
      critMultiplier: 1.5,
      attackZones: 2,
      defendZones: 2,
    },
  ],
};
